server:
  context-path: /share
  port: 9090
spring:
  profiles:
    active: dev
  jpa:
    database: MYSQL
    show-sql: false
    physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    format-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
